export const ADD_STRIP = 'ADD_STRIP';
export const REMOVE_STRIP = 'REMOVE_STRIP';
export const ADD_AVAILABLE_STRIP = 'ADD_AVAILABLE_STRIP';
export const CLEAR_AVAILABLE_STRIPS = 'CLEAR_AVAILABLE_STRIP';
export const SET_SCANNING_STATE = 'SET_SCANNING_STATE';
